FROM pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel

RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y install bash \
        build-essential \
        wget \
        curl \
        openssh-server \
        git \
        openssh-client && \
    apt-get clean

WORKDIR /root

RUN pip install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl