FROM pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel

RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y install bash \
        build-essential \
        wget \
        curl \
        openssh-server \
        git \
        openssh-client && \
    apt-get clean

WORKDIR /root

RUN pip install absl-py scipy numpy

RUN pip uninstall -y torchvision

RUN git clone https://github.com/pytorch/vision.git

WORKDIR /root/vision

RUN python setup.py install

WORKDIR /root
