sets = [
  # ['squeezenetv1_0_cmd'],
  # ['googlenet_cmd'],
  # ['inceptionv3_cmd'],
  # ['mobilenetv2_cmd'],
  # ['densenet121_cmd'],
  # ['densenet169_cmd'],
  # ['resnet18_cmd'],
  # ['resnet34_cmd'],
  # ['resnet50_cmd'],
  # ['shufflenet_1_0_cmd'],
  ['mobilenetv2_large_cmd'],
  ['densenet161_cmd'],
  ['resnext29_2x64_cmd'],
#  'vgg19_cmd',
  # ['efficientnetb0_cmd'],
  # ['efficientnetb1_cmd'],
  # ['efficientnetb2_cmd'],
  # ['efficientnetb3_cmd'],
  # ['efficientnetb4_cmd'],
  # ['efficientnetb0_cmd', 'resnet_cmd'],
  # ['efficientnetb0_cmd', 'googlenet_cmd'],
  # ['efficientnetb0_cmd', 'vgg19_cmd'],
  # ['efficientnetb0_cmd', 'mobilenetv2_cmd'],
  # ['efficientnetb0_cmd', 'lm_cmd'],
  # ['efficientnetb0_cmd', 'mt2_cmd'],
  # ['efficientnetb3_cmd', 'resnet_cmd'],
  # ['efficientnetb3_cmd', 'googlenet_cmd'],
  # ['efficientnetb3_cmd', 'vgg19_cmd'],
  # ['efficientnetb3_cmd', 'mobilenetv2_cmd'],
  # ['efficientnetb3_cmd', 'lm_cmd'],
  # ['efficientnetb3_cmd', 'mt2_cmd'],
    # ['googlenet_cmd'],
    # ['googlenet_cmd', 'googlenet_cmd'],
    # ['googlenet_cmd', 'pos_cmd'],
    # ['googlenet_cmd', 'lm_cmd'],
    # ['googlenet_cmd', 'resnet_cmd'],
    # ['mobilenetv2_cmd'],
    # ['mobilenetv2_cmd', 'mobilenetv2_cmd'],
    # ['mobilenetv2_cmd', 'mobilenetv2_cmd', 'mobilenetv2_cmd'],
    # ['mobilenetv2_cmd', 'resnet_cmd'],
    # ['mobilenetv2_cmd', 'vgg19_cmd'],
    # ['mobilenetv2_large_cmd'],
    # ['mobilenetv2_large_cmd', 'mobilenetv2_large_cmd'],
    # ['mobilenetv2_large_cmd', 'mobilenetv2_large_cmd', 'mobilenetv2_large_cmd'],
    # ['mobilenetv2_large_cmd', 'resnet_cmd'],
    # ['mobilenetv2_large_cmd', 'vgg19_cmd'],
    # ['lm_med_cmd'],
    # ['lm_med_cmd', 'resnet_cmd'],
    # ['lm_med_cmd', 'lm_med_cmd'],
    # ['lm_med_cmd', 'vgg19_cmd'],
    # ['resnet_cmd'],
    # ['resnet_cmd', 'mt2_cmd'],
    # ['resnet_cmd', 'lm_cmd'],
    # ['resnet_cmd', 'lm_large_cmd'],
    # ['resnet_cmd', 'resnet_cmd'],
    # ['vgg19_cmd'],
    # ['lm_cmd', 'vgg19_cmd'],
    # ['lm_large_cmd', 'vgg19_cmd'],
    # ['vgg19_cmd', 'vgg19_cmd'],
    # ['pos_cmd'],
    # ['pos_cmd', 'pos_cmd'],
    # ['lm_cmd'],
    # ['lm_cmd', 'lm_cmd'],
    # ['lm_cmd', 'lm_large_cmd'],
    # ['lm_cmd', 'pos_cmd'],
    # ['lm_large_cmd'],
    # ['mt2_cmd'],
    # ['mt2_cmd', 'mt2_cmd'],
    # ['mt2_cmd', 'googlenet_cmd'],
    # ['mt2_cmd', 'mobilenetv2_cmd'],
    # ['mt2_cmd', 'resnet_cmd'],
    # ['mt2_cmd', 'vgg19_cmd']
]