sets = [
    # ['googlenet_cmd'],
    # ['googlenet_cmd', 'googlenet_cmd'],
    # ['googlenet_cmd', 'pos_cmd'],
    # ['googlenet_cmd', 'lm_cmd'],
    # ['googlenet_cmd', 'resnet_cmd'],
    # ['mobilenetv2_cmd'],
    # ['mobilenetv2_cmd', 'mobilenetv2_cmd'],
    # ['mobilenetv2_cmd', 'mobilenetv2_cmd', 'mobilenetv2_cmd'],
    # ['mobilenetv2_cmd', 'resnet_cmd'],
    # ['mobilenetv2_cmd', 'vgg19_cmd'],
    ['mobilenetv2_large_cmd'],
    ['mobilenetv2_large_cmd', 'mobilenetv2_large_cmd'],
    ['mobilenetv2_large_cmd', 'mobilenetv2_large_cmd', 'mobilenetv2_large_cmd'],
    ['mobilenetv2_large_cmd', 'resnet_cmd'],
    ['mobilenetv2_large_cmd', 'vgg19_cmd'],
    ['lm_med_cmd'],
    ['lm_med_cmd', 'resnet_cmd'],
    ['lm_med_cmd', 'lm_med_cmd'],
    ['lm_med_cmd', 'vgg19_cmd'],
    # ['resnet_cmd'],
    # ['resnet_cmd', 'mt2_cmd'],
    # ['resnet_cmd', 'lm_cmd'],
    # ['resnet_cmd', 'lm_large_cmd'],
    # ['resnet_cmd', 'resnet_cmd'],
    # ['vgg19_cmd'],
    # ['lm_cmd', 'vgg19_cmd'],
    # ['lm_large_cmd', 'vgg19_cmd'],
    # ['vgg19_cmd', 'vgg19_cmd'],
    # ['pos_cmd'],
    # ['pos_cmd', 'pos_cmd'],
    # ['lm_cmd'],
    # ['lm_cmd', 'lm_cmd'],
    # ['lm_cmd', 'lm_large_cmd'],
    # ['lm_cmd', 'pos_cmd'],
    # ['lm_large_cmd'],
    # ['mt2_cmd'],
    # ['mt2_cmd', 'mt2_cmd'],
    # ['mt2_cmd', 'googlenet_cmd'],
    # ['mt2_cmd', 'mobilenetv2_cmd'],
    # ['mt2_cmd', 'resnet_cmd'],
    # ['mt2_cmd', 'vgg19_cmd']
]