sets = [
  ['googlenet_cmd'],
  ['mobilenetv2_cmd'],
  ['vgg19_cmd'],
  ['resnet_cmd'],
  ['pos_cmd'],
  ['mt1_cmd'],
  ['mt2_cmd'],
  ['lm_cmd'],
  ['googlenet_cmd','googlenet_cmd'],
  ['mobilenetv2_cmd','mobilenetv2_cmd'],
  ['pos_cmd', 'pos_cmd'],
  ['resnet_cmd', 'resnet_cmd'],
  ['googlenet_cmd', 'mobilenetv2_cmd'],
  ['googlenet_cmd', 'vgg19_cmd'],
  ['googlenet_cmd', 'pos_cmd'],
  ['googlenet_cmd', 'mt1_cmd'],
  ['googlenet_cmd', 'mt2_cmd'],
  ['googlenet_cmd', 'lm_cmd'],
  ['googlenet_cmd', 'resnet_cmd'],
  ['mobilenetv2_cmd', 'vgg19_cmd'],
  ['mobilenetv2_cmd', 'pos_cmd'],
  ['mobilenetv2_cmd', 'mt1_cmd'],
  ['mobilenetv2_cmd', 'mt2_cmd'],
  ['mobilenetv2_cmd', 'lm_cmd'],
  ['mobilenetv2_cmd', 'resnet_cmd']
]